# Generated by Django 4.2.7 on 2026-01-20 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=255)),
                ('problem_link', models.URLField(blank=True, max_length=500, null=True)),
                ('platform', models.CharField(choices=[('LEETCODE', 'LeetCode'), ('GFG', 'GeeksforGeeks'), ('CODEFORCES', 'CodeForces')], default='LEETCODE', max_length=20)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=10)),
                ('tags', models.JSONField(default=list, help_text='Array of problem tags')),
                ('status', models.CharField(choices=[('SOLVED', 'Solved'), ('ATTEMPTED', 'Attempted'), ('TO_REVISE', 'To Revise')], default='ATTEMPTED', max_length=15)),
                ('solved_count', models.PositiveIntegerField(default=0)),
                ('last_solved', models.DateTimeField(blank=True, null=True)),
                ('next_revision_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Problem',
                'verbose_name_plural': 'Problems',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approach', models.CharField(choices=[('BRUTE_FORCE', 'Brute Force'), ('BETTER', 'Better'), ('OPTIMAL', 'Optimal')], default='OPTIMAL', max_length=20)),
                ('language', models.CharField(choices=[('JAVA', 'Java'), ('PYTHON', 'Python'), ('CPP', 'C++'), ('JAVASCRIPT', 'JavaScript')], default='PYTHON', max_length=20)),
                ('code', models.TextField(help_text='Full solution code')),
                ('time_complexity', models.CharField(blank=True, help_text='e.g., O(n log n)', max_length=100)),
                ('space_complexity', models.CharField(blank=True, help_text='e.g., O(n)', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or explanation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='problems.problem')),
            ],
            options={
                'verbose_name': 'Solution',
                'verbose_name_plural': 'Solutions',
                'ordering': ['-created_at'],
            },
        ),
    ]
