# Generated by Django 4.2.7 on 2026-01-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='test_cases',
            field=models.JSONField(blank=True, default=list, help_text='Array of test cases with input and expected output. Format: [{"input": "...", "output": "...", "explanation": "..."}]'),
        ),
    ]
